# golangci-lint configuration (schema-compatible with v1.64+)
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    settings:
      shadow:
        strict: false

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: github.com/hidatara-ds/evolipia-radar

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport

  funlen:
    lines: 80
    statements: 50

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
      - TODO
      - BUG
      - FIXME

  cyclop:
    max-complexity: 15
    package-average: 10

  nestif:
    min-complexity: 5

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - cyclop
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - sqlclosecheck
    - tagliatelle
    - thelper
    - wastedassign
    - wrapcheck

  disable:
    - depguard
    - exhaustivestruct
    - gochecknoglobals
    - gomnd
    - ireturn
    - lll
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - funlen
        - gocognit
        - gochecknoglobals
        - gochecknoinits

    - text: "weak cryptographic primitive"
      linters:
        - gosec

    - path: _test\.go
      text: "shadow"
      linters:
        - govet

    - text: 'shadow: declaration of "err"'
      linters:
        - govet

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
